# Generated by Django 5.0 on 2023-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshitapp', '0003_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
