# Generated by Django 5.0 on 2023-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surakshitapp', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
